Update dbsetup.sql
On linux the mariadb server is case sensitive at default.
This change prevents the following error in console:
java.sql.SQLSyntaxErrorException: Table 's2_TempFly.tempfly_data' doesn't exist